ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,18 +1,10 @@
-name: Moodle Plugin CI for local_oauth2
+name: Moodle Plugin CI
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
-
-on:
-  push:
-    branches:
-      - 'MOODLE_*_STABLE'
-  pull_request:
+on: [push, pull_request]
 
 jobs:
-  check:
-    runs-on: ubuntu-latest
+  test:
+    runs-on: ubuntu-22.04
 
     services:
       postgres:
@@ -21,7 +13,7 @@ jobs:
           POSTGRES_USER: 'postgres'
           POSTGRES_HOST_AUTH_METHOD: 'trust'
         ports:
-          - 5432:5432
+        - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
 
       mariadb:
@@ -31,96 +23,92 @@ jobs:
           MYSQL_ALLOW_EMPTY_PASSWORD: "true"
           MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
           MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
-          MYSQL_INNODB_FILE_PER_TABLE: "1"
-          MYSQL_INNODB_FILE_FORMAT: "Barracuda"
         ports:
-          - 3306:3306
+        - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
 
     strategy:
       fail-fast: false
       matrix:
-        moodle-branch: ['MOODLE_405_STABLE']
-        php: [8.1, 8.2, 8.3]
+        php: ['8.1', '8.2', '8.3', '8.4']
+        moodle-branch: ['MOODLE_405_STABLE', 'MOODLE_404_STABLE']
         database: [pgsql, mariadb]
 
     steps:
-      - name: Check out repository code
-        uses: actions/checkout@v4
-        with:
-          path: plugin
+    - name: Check out repository code
+      uses: actions/checkout@v4
+      with:
+        path: plugin
 
-      - name: Setup PHP ${{ matrix.php }}
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ matrix.php }}
-          ini-values: max_input_vars=5000
-          coverage: none
+    - name: Setup PHP ${{ matrix.php }}
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: ${{ matrix.php }}
+        extensions: ${{ matrix.extensions }}
+        ini-values: max_input_vars=5000
+        # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
+        # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
+        coverage: none
 
-      - name: Initialise moodle-plugin-ci
-        run: |
-          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
-          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
-          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
-          sudo locale-gen en_AU.UTF-8
-          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
+    - name: Initialise moodle-plugin-ci
+      run: |
+        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
+        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
+        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+        sudo locale-gen en_AU.UTF-8
+        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
 
-      - name: Install moodle-plugin-ci
-        run: |
-          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
-        env:
-          DB: ${{ matrix.database }}
-          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
-          SHELLOPTS: errexit:nounset:xtrace
+    - name: Install moodle-plugin-ci
+      run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
+      env:
+        DB: ${{ matrix.database }}
+        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+        # Uncomment this to run Behat tests using the Moodle App.
+        # MOODLE_APP: 'true'
 
-      - name: PHP Lint
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phplint
+    - name: PHP Lint
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phplint
 
-      - name: PHP Mess Detector
-        continue-on-error: true
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpmd
+    - name: PHP Mess Detector
+      continue-on-error: true # This step will show errors but will not fail
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpmd
 
-      - name: Moodle Code Checker
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpcs --max-warnings 0
+    - name: Moodle Code Checker
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpcs --max-warnings 0
 
-      - name: Moodle PHPDoc Checker
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpdoc --max-warnings 0
+    - name: Validating
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci validate
 
-      - name: Validating
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci validate
+    - name: Check upgrade savepoints
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci savepoints
 
-      - name: Check upgrade savepoints
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci savepoints
+    - name: Mustache Lint
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci mustache
 
-      - name: Mustache Lint
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci mustache
+    - name: PHPUnit tests
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpunit --fail-on-warning
 
-      - name: Grunt
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci grunt --max-lint-warnings 0
+    - name: Behat features
+      id: behat
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci behat --profile chrome
 
-      - name: PHPUnit tests
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpunit
+    - name: Upload Behat Faildump
+      if: ${{ failure() && steps.behat.outcome == 'failure' }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: Behat Faildump (${{ join(matrix.*, ', ') }})
+        path: ${{ github.workspace }}/moodledata/behat_dump
+        retention-days: 7
+        if-no-files-found: ignore
 
-      - name: Behat features
-        id: behat
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci behat --profile chrome
-
-      - name: Cleanup after behat
-        if: ${{ always() }}
-        run: |
-          sudo pkill -f chrome
-          sudo pkill -f chromedriver
-
-      - name: Mark cancelled jobs as failed.
-        if: ${{ cancelled() }}
-        run: exit 1
+    - name: Mark cancelled jobs as failed.
+      if: ${{ cancelled() }}
+      run: exit 1
